version: 0.2

env:
  variables:
    TF_IN_AUTOMATION: "true"
phases:
  install:
    commands:
      - curl -sSLo terraform.zip https://releases.hashicorp.com/terraform/1.7.5/terraform_1.7.5_linux_amd64.zip
      - unzip -o terraform.zip -d /usr/local/bin
      - terraform -version
  pre_build:
    commands:
      - terraform init -input=false
  build:
    commands:
      - terraform fmt -recursive
      - terraform validate
      - |
        APP_NAME=$(grep -E '^\s*application_name\s*=' terraform.tfvars 2>/dev/null | sed -E 's/.*=\s*"?([^"]+)"?/\1/' | head -1 || echo "equity-management")
        ENV_NAME=$(grep -E '^\s*environment\s*=' terraform.tfvars 2>/dev/null | sed -E 's/.*=\s*"?([^"]+)"?/\1/' | head -1 || echo "${ENVIRONMENT:-production}")
        ROLE_NAME="${APP_NAME}-${ENV_NAME}-lambda-execution-role"
        if ! terraform state list 2>/dev/null | grep -q "module.lambda_iam.aws_iam_role.this"; then
          if aws iam get-role --role-name "$ROLE_NAME" >/dev/null 2>&1; then
            terraform import -input=false module.lambda_iam.aws_iam_role.this "$ROLE_NAME" || true
          fi
        fi
      - terraform plan -input=false -out=tfplan
      - terraform apply -input=false -auto-approve tfplan
artifacts:
  files:
    - '**/*'
  discard-paths: yes


